// Generated by scripts/gen-tool-pages.mjs — do not edit by hand.
import { createToolIsland } from '~/components/createToolIsland';
import App from './App';
import commonEn from '~/i18n/client/en.json';
import commonZh from '~/i18n/client/zh.json';
import toolEn from './i18n/en.json';
import toolZh from './i18n/zh.json';

export default createToolIsland(App, {
    en: { ...commonEn, ...toolEn },
    zh: { ...commonZh, ...toolZh },
});
