// Tool slugs that have generated pages. The legacy pipeline derived this from
// the Vite bundle manifest; here we check for the per-tool island wrapper
// (src/tools/<slug>/ToolIsland.tsx) generated by scripts/gen-tool-pages.mjs,
// falling back to the legacy entries/ marker. A tool registered in
// data/tools.ts without either is skipped (same behavior, no build step).
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { TOOLS } from './tools';

// Astro bundles page modules for SSR and rewrites import.meta.url, so resolve
// against process.cwd() (astro dev/build always run from the project root).
const rootDir = process.cwd();

function hasToolEntry(slug: string): boolean {
    return (
        existsSync(resolve(rootDir, 'src/tools', slug, 'ToolIsland.tsx')) ||
        existsSync(resolve(rootDir, 'src/tools', slug, 'entries/en.tsx'))
    );
}

// The legacy generate-pages.tsx sorted migrated tool slugs alphabetically
// (from the manifest key order), which determines card order within each
// category on the home page — keep the same ordering.
export const MIGRATED_TOOLS: string[] = TOOLS.filter((tool) => hasToolEntry(tool.slug))
    .map((tool) => tool.slug)
    .sort();
